In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
array_1=np.arange(0,20+1)
print(array_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
#2.呈上題，將以上數列取出偶數。
A=np.arange(0,21,2)
print(A)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [12]:
#3.呈1題，將數列取出3的倍數。
B=np.arange(0,21,3)
print(B)

[ 0  3  6  9 12 15 18]
